#!/usr/bin/python

import sys
import telnetlib

if len(sys.argv)<2:
    print "ERROR: need ip address as argument!"
    sys.exit(2)
address = sys.argv[1]
port = '6556'
try:
    tn = telnetlib.Telnet(address, port, 1)
except:
    print("couldnt connect")
    sys.exit(2)
out = tn.read_all()
if len(out)> 300:
    output = address
    with open(output, 'w') as f:
        f.write(out)
        print 'OK'
        sys.exit(0)
    print("couldnt write file")
    sys.exit(2)
else:
    print 'ERROR, telnet output to short:\n' + out
    sys.exit(2)
print("ERROR, program did nothing")
sys.exit(2)

