#!/usr/bin/python

#
# Copyright 2018 Nikolas Hagemann comNET GmbH <nikolas.hagemann@comnetgmbh.com>
#
# This file is part of check_cmkagent.
#
# check_cmkagent is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# check_cmkagent is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with check_cmkagent.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import telnetlib

if len(sys.argv)<2:
    print "ERROR: need ip address as argument!"
    sys.exit(2)
address = sys.argv[1]
port = '6556'
try:
    tn = telnetlib.Telnet(address, port, 1)
except:
    print("couldnt connect")
    sys.exit(2)
out = tn.read_all()
if len(out)> 300:
    output = '/var/lib/check_cmkagent/' + address
    with open(output, 'w') as f:
        f.write(out)
        print 'OK'
        sys.exit(0)
    print("couldnt write file")
    sys.exit(2)
else:
    print 'ERROR, telnet output to short:\n' + out
    sys.exit(2)
print("ERROR, program did nothing")
sys.exit(2)

